env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"

steps:
  - label: ":lint-roller::bash: Lint Bash"
    command:
      - make lint-bash

  - label: ":lint-roller::buildkite: Lint Plugin"
    command:
      - make lint-plugin

  # TODO: Add some unit tests!
  # - label: ":lint-roller::buildkite: Test Plugin"
  #   command:
  #     - make test-plugin

  - label: ":buildkite::vault: Run Plugin 1"
    command: echo 'Hello World'
    plugins:
      - "ssh://git@github.com/grapl-security/vault-login-buildkite-plugin#72a5d02":
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - "ssh://git@github.com/grapl-security/vault-env-buildkite-plugin#${BUILDKITE_COMMIT}":
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
          secrets:
            - secret/data/buildkite/env/TOOLCHAIN_AUTH_TOKEN
            - secret/data/buildkite/env/CLOUDSMITH_TOKEN
    agents:
      queue: "docker/cm-testing"


  - label: ":buildkite::vault: Run Plugin 2"
    command: echo 'Hello World'
    plugins:
      - "ssh://git@github.com/grapl-security/vault-login-buildkite-plugin#72a5d02":
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - "ssh://git@github.com/grapl-security/vault-env-buildkite-plugin#${BUILDKITE_COMMIT}":
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
          secret_prefix: secret/data/buildkite
          secrets:
            - env/TOOLCHAIN_AUTH_TOKEN
            - env/CLOUDSMITH_TOKEN
    agents:
      queue: "docker/cm-testing"

  - label: ":buildkite::vault: Run Plugin 3"
    command: echo 'Hello World'
    plugins:
      - "ssh://git@github.com/grapl-security/vault-login-buildkite-plugin#72a5d02":
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - "ssh://git@github.com/grapl-security/vault-env-buildkite-plugin#${BUILDKITE_COMMIT}":
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
          secret_prefix: secret/data/buildkite/env
          secrets:
            - TOOLCHAIN_AUTH_TOKEN
            - CLOUDSMITH_TOKEN
    agents:
      queue: "docker/cm-testing"

  - label: ":buildkite::vault: Run Plugin 4"
    command: echo 'Hello World'
    plugins:
      - "ssh://git@github.com/grapl-security/vault-login-buildkite-plugin#72a5d02":
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - "ssh://git@github.com/grapl-security/vault-env-buildkite-plugin#${BUILDKITE_COMMIT}":
          secret_prefix: secret/data/buildkite/env/
          secrets:
            - TOOLCHAIN_AUTH_TOKEN
            - CLOUDSMITH_TOKEN
    agents:
      queue: "docker/cm-testing"
  - label: ":buildkite::vault: Run Plugin 5"
    command: echo 'Hello World'
    plugins:
      - "ssh://git@github.com/grapl-security/vault-login-buildkite-plugin#72a5d02":
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - "ssh://git@github.com/grapl-security/vault-env-buildkite-plugin#${BUILDKITE_COMMIT}":
          secret_prefix: secret/data/buildkite/env/
          secrets:
            - CLOUDSMITH_TOKEN
      - "ssh://git@github.com/grapl-security/vault-env-buildkite-plugin#${BUILDKITE_COMMIT}":
          secrets:
            - secret/data/buildkite/env/TOOLCHAIN_AUTH_TOKEN
    agents:
      queue: "docker/cm-testing"
