env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"

steps:
  - label: ":pants: All files are covered by Pants"
    command:
      - ./pants tailor --check

  - label: ":lint-roller::bash: Lint Shell"
    command:
      - make lint-shell
    plugins:
      - grapl-security/vault-login#v0.1.3
      - grapl-security/vault-env#v0.2.0:
          secrets:
            - secret/data/buildkite/env/vault-env-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN

  - label: ":lint-roller::buildkite: Lint Plugin"
    command:
      - make lint-plugin

  - label: ":lint-roller::buildkite: Test Plugin"
    command:
      - make test-plugin

  - label: ":buildkite::vault: Run Plugin 1"
    command: echo 'Hello World'
    plugins:
      - grapl-security/vault-login#v0.1.3:
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - grapl-security/vault-env#${BUILDKITE_COMMIT}:
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
          secrets:
            - secret/data/buildkite/env/vault-env-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN
            - secret/data/buildkite/env/CLOUDSMITH_API_KEY
    agents:
      queue: "docker"

  - label: ":buildkite::vault: Run Plugin 2"
    command: echo 'Hello World'
    plugins:
      - grapl-security/vault-login#v0.1.3:
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - grapl-security/vault-env#${BUILDKITE_COMMIT}:
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
          secret_prefix: secret/data/buildkite
          secrets:
            - env/vault-env-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN
            - env/CLOUDSMITH_API_KEY
    agents:
      queue: "docker"

  - label: ":buildkite::vault: Run Plugin 3"
    command: echo 'Hello World'
    plugins:
      - grapl-security/vault-login#v0.1.3:
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - grapl-security/vault-env#${BUILDKITE_COMMIT}:
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
          secret_prefix: secret/data/buildkite/env
          secrets:
            - vault-env-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN
            - CLOUDSMITH_API_KEY
    agents:
      queue: "docker"

  - label: ":buildkite::vault: Run Plugin 4"
    command: echo 'Hello World'
    plugins:
      - grapl-security/vault-login#v0.1.3:
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - grapl-security/vault-env#${BUILDKITE_COMMIT}:
          secret_prefix: secret/data/buildkite/env/
          secrets:
            - vault-env-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN
            - CLOUDSMITH_API_KEY
    agents:
      queue: "docker"

  - label: ":buildkite::vault: Run Plugin 5"
    command: echo 'Hello World'
    plugins:
      - grapl-security/vault-login#v0.1.3:
          # These two can be set globally before the vault-login plugin is invoked
          namespace: "admin/buildkite"
          address: "https://vault-cluster.private.vault.b3b89729-5226-4b15-8c8a-b42572e88e7c.aws.hashicorp.cloud:8200"
      - grapl-security/vault-env#${BUILDKITE_COMMIT}:
          secret_prefix: secret/data/buildkite/env/
          secrets:
            - CLOUDSMITH_API_KEY
      - grapl-security/vault-env#${BUILDKITE_COMMIT}:
          secrets:
            - secret/data/buildkite/env/vault-env-buildkite-plugin/TOOLCHAIN_AUTH_TOKEN
    agents:
      queue: "docker"
