#!/usr/bin/env bash

set -euo pipefail

# shellcheck source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/../lib/log.sh"

readonly default_image="hashicorp/envconsul"
readonly default_tag="latest"
readonly image="${BUILDKITE_PLUGIN_VAULT_ENV_IMAGE:-${default_image}}:${BUILDKITE_PLUGIN_VAULT_ENV_TAG:-${default_tag}}"

# Fail if there is no Vault token; gotta log in first
########################################################################
if [ -z "${VAULT_TOKEN:-}" ]; then
    raise_error "Could not find 'VAULT_TOKEN' in the environment!"
fi

# Resolve Vault address
########################################################################
if [ -n "${BUILDKITE_PLUGIN_VAULT_ENV_ADDRESS:-}" ]; then
    VAULT_ADDR="${BUILDKITE_PLUGIN_VAULT_ENV_ADDRESS}"
    export VAULT_ADDR
fi
if [ -z "${VAULT_ADDR:-}" ]; then
    raise_error "Could not find 'VAULT_ADDR' in the environment, and 'BUILDKITE_PLUGIN_VAULT_ENV_ADDRESS' was not specified!"
fi

# Resolve Vault namespace
########################################################################
if [ -n "${BUILDKITE_PLUGIN_VAULT_ENV_NAMESPACE:-}" ]; then
    VAULT_NAMESPACE="${BUILDKITE_PLUGIN_VAULT_ENV_NAMESPACE}"
    export VAULT_NAMESPACE
fi
if [ -z "${VAULT_NAMESPACE:-}" ]; then
    raise_error "Could not find 'VAULT_NAMESPACE' in the environment, and 'BUILDKITE_PLUGIN_VAULT_ENV_NAMESPACE' was not specified!"
fi

# Resolve secret prefix
########################################################################
secret_prefix="${BUILDKITE_PLUGIN_VAULT_ENV_SECRET_PREFIX:-}"

# If `secret_prefix` is not empty, and does not already end with a `/`, add a `/`
if [[ -n "${secret_prefix}" && ! "${secret_prefix}" =~ /$ ]]; then
    secret_prefix="${secret_prefix}/"
fi
readonly secret_prefix

# Resolve secrets
########################################################################

# STOLEN FROM https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/9f90d8ef742d9fa1eb3556720e16f2b842ff1cb2/hooks/command#L25-L47
#
# Reads a list from plugin config into a global result array
# Returns success if values were read
plugin_read_list_into_result() {
    result=()

    for prefix in "$@"; do
        local i=0
        local parameter="${prefix}_${i}"

        if [[ -n "${!prefix:-}" ]]; then
            raise_error "Plugin received a string for $prefix, expected an array"
        fi

        while [[ -n "${!parameter:-}" ]]; do
            result+=("${!parameter}")
            i=$((i + 1))
            parameter="${prefix}_${i}"
        done
    done

    [[ ${#result[@]} -gt 0 ]] || return 1
}

secrets=()
if plugin_read_list_into_result BUILDKITE_PLUGIN_VAULT_ENV_SECRETS; then
    secrets=("${result[@]}")
else
    raise_error "At least one secret must be specified!"
fi

########################################################################

readonly container_name="vault-env-plugin-${BUILDKITE_JOB_ID}"

envconsul_env() {
    args=()
    for secret in "${secrets[@]}"; do
        # secret_prefix is guaranteed to end with a / if it is non-empty
        args+=("-secret=${secret_prefix}${secret}")
    done

    # Explicitly *not* using `--rm` so we can output the container
    # logs in case of a failure.
    log_and_run docker run \
        --env VAULT_TOKEN \
        --name="${container_name}" \
        -- \
        "${image}" \
        "${args[@]}" \
        -once \
        -upcase \
        -pristine \
        -no-prefix=true \
        -vault-addr="${VAULT_ADDR}" \
        -vault-namespace="${VAULT_NAMESPACE}" \
        -vault-renew-token=false \
        -vault-retry-attempts=1 \
        env
}

cleanup() {
    log_and_run docker container rm --force "${container_name}" > /dev/null 2>&1
}

trap cleanup EXIT INT QUIT

log "--- :vault: Pulling secrets from Vault"
log "Using Docker image: ${image}"
log "VAULT_ADDR=${VAULT_ADDR}"
log "VAULT_NAMESPACE=${VAULT_NAMESPACE}"

if vault_env=$(envconsul_env); then
    set -o allexport
    eval "${vault_env}"
    set +o allexport
else
    retval=$?
    log "--- :skull_and_crossbones: Failed to retrieve secrets from Vault"
    log_and_run docker container logs "${container_name}"
    exit ${retval}
fi
